const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'ig-content-studio.html'), 'utf8');
const script = source.match(/<script>([\s\S]*?)<\/script>/)[1].split('/* ===== init ===== */')[0];
const memory = new Map(), storage = {getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
const fields = {doi:{value:'10.1000/example'}};
const context = vm.createContext({console, localStorage:storage, sessionStorage:storage, URL, Blob, setTimeout, clearTimeout,
  document:{getElementById:id=>fields[id]||{value:''}, querySelectorAll:()=>[]}});
vm.runInContext(script, context);
const run = code => vm.runInContext(code, context);
const json = code => JSON.parse(run('JSON.stringify(' + code + ')'));
context.renderOutput = ()=>{}; context.renderTab = ()=>{}; context.renderGraphicTab = ()=>{}; context.toast=()=>{};
const prompt = run('aiArtPrompt_({style:"analogy",audience:"general",text:"none",format:"portrait",direction:"Warm colors"},"Nickel oxide surfaces were treated with acetylacetone.")');
assert.ok(prompt.includes('Warm colors'));
assert.ok(prompt.includes('Nickel oxide'));
assert.ok(prompt.includes('No text, labels'));
assert.ok(prompt.includes('Never invent results'));
assert.ok(prompt.includes('No University of Rochester branding'));
assert.ok(prompt.includes('everyday visual analogy'));
const request = json('openAIArtRequest_("Scientific facts",{format:"portrait",quality:"invalid"})');
assert.equal(request.size,'1024x1280');
assert.equal(request.output_format,'jpeg');
assert.equal(request.n,1);
assert.equal(request.quality,'medium');
assert.equal(request.apiKey,undefined);
assert.equal(json('openAIArtRequest_("Facts",{format:"square",quality:"low"})').size,'1024x1024');
assert.throws(()=>run('normalizeAIDiagram_(null)'),/readable/);
assert.throws(()=>run('normalizeAIDiagram_({steps:[null,{}]})'),/at least two/);
const normalized=json('normalizeAIDiagram_({title:"x".repeat(1000),background:"url(evil)",ink:"#123456",steps:[{icon:"<script>"},{icon:"atom"},{icon:"leaf"},{icon:"flow"}]})');
assert.equal(normalized.steps.length,3); assert.equal(normalized.steps[0].icon,'layers');
assert.equal(normalized.title.length,85); assert.equal(normalized.background,'#F7F3EA');
run('activeType="paper";paperMeta={title:"Paper title",journal:"Journal",authors:"A. Author",year:"2026"};reviewSource=null;initOutput({caption:"Original caption",headline:"Headline"},{brief:"Paper source",meta1:"Journal",meta2:"2026"});');
run('paperGalleryDraft.title="Edited article title";paperGalleryDraft.enabled=false;applyAIArt_({dataUrl:"data:image/jpeg;base64,test",format:"portrait",alt:"Conceptual thin film illustration"});');
assert.equal(run('currentGraphic.template'),'art');
assert.equal(run('currentGraphic.figure'),'data:image/jpeg;base64,test');
assert.equal(json('graphicSize(currentGraphic.template)').height,1350);
run('initOutput({caption:"Fresh caption",headline:"Fresh title"},{brief:"Paper source",meta1:"Journal",meta2:"2026"});');
assert.equal(run('currentGraphic.template'),'art','caption regeneration must retain artwork for the same paper');
assert.equal(run('current.caption'),'Fresh caption');
assert.equal(run('current.alt_text'),'Conceptual thin film illustration');
assert.equal(run('paperGalleryDraft.title'),'Edited article title');
assert.equal(run('paperGalleryDraft.enabled'),false,'caption regeneration must preserve the gallery opt-out');
run('restoreAIArt_();'); assert.equal(run('currentGraphic.template'),'paper');
run('applyAIArt_({dataUrl:"old-paper-image",format:"square",alt:"Old paper"});initOutput({headline:"Different paper"},{brief:"Different paper source"});');
assert.equal(run('currentGraphic.generatedImage'),undefined,'changing papers must not reuse the previous illustration');
run('paperGalleryDraft={enabled:true,title:"Paper title",articleUrl:"10.1000/article"};');
assert.equal(json('approvalPaperGallery_()').articleUrl,'https://doi.org/10.1000/article');
run('paperGalleryDraft.articleUrl="javascript:alert(1)";');
assert.throws(()=>run('approvalPaperGallery_()'),/link|URL/i);
console.log('AI prompt, provider request, diagram validation, artwork preservation and gallery editing passed');
