const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'..','ig-content-studio.html'),'utf8');
const script=source.match(/<script>([\s\S]*?)<\/script>/)[1].split('/* ===== init ===== */')[0];
const fields={doi:{value:'10.1000/example'},paperText:{value:'Surface treatment changes nickel oxide thin-film conductivity.'},paperAngle:{value:''},paperCredit:{value:'Shestopalov group'},creativeDirection:{value:''}};
const storage={getItem:()=>null,setItem:()=>{}};
const context=vm.createContext({console,URL,Blob,setTimeout,clearTimeout,localStorage:storage,sessionStorage:storage,document:{getElementById:id=>fields[id]||(fields[id]={value:'',textContent:'',innerHTML:''}),querySelectorAll:()=>[]}});
vm.runInContext(script,context);
const run=code=>vm.runInContext(code,context),json=code=>JSON.parse(run('JSON.stringify('+code+')'));
context.renderOutput=()=>{};context.renderTab=()=>{};context.renderGraphicTab=()=>{};context.renderPaperMeta=()=>{};context.toast=()=>{};context.getApiKey=()=> 'local-test-key';
assert.deepEqual(json('paperCaptionIssues_("We found that our treatment improves conductivity.",{paperCredit:"Shestopalov group"})').length,2);
assert.deepEqual(json('paperCaptionIssues_("The Shestopalov group studied surface chemistry.",{paperCredit:"Shestopalov group"})'),[]);
assert.equal(run('withPaperBio_(withPaperBio_("A paper from the Shestopalov group."))'),'A paper from the Shestopalov group.\n\nRead the paper via the link in bio.');
assert.equal(run('withPaperBio_("Read the paper: link in bio.")'),'Read the paper: link in bio.');
assert.equal(run('withPaperBio_("")'),'');
run('activeType="paper";initOutput({headline:"Surface chemistry"},buildSourceBrief_());applyAIArt_({dataUrl:"selected-ai-image",format:"portrait",alt:"Conceptual thin film"});paperGalleryDraft.title="Full article title";');
fields.paperAngle.value='Emphasize the material';fields.paperCredit.value='Alexander Shestopalov and colleagues';
assert.equal(run('sameDraftSource_(buildSourceBrief_())'),true,'angle and credit edits must not change which paper owns the image');
run('initOutput({caption:"New caption"},buildSourceBrief_());');
assert.equal(run('currentGraphic.figure'),'selected-ai-image');assert.equal(run('paperGalleryDraft.title'),'Full article title');
fields.doi.value='https://doi.org/10.1000/EXAMPLE';assert.equal(run('sameDraftSource_(buildSourceBrief_())'),true,'DOI spellings must identify the same paper');
fields.doi.value='10.1000/different';assert.equal(run('sameDraftSource_(buildSourceBrief_())'),false);
fields.doi.value='10.1000/example';fields.paperCredit.value='Shestopalov group';
const response=caption=>({ok:true,status:200,json:async()=>({content:[{type:'text',text:JSON.stringify({caption,headline:'A clearer headline',hashtags:[]})}]})});
(async()=>{
  const requests=[];context.fetch=async(url,options)=>{requests.push(JSON.parse(options.body));return response(requests.length===1?'We changed how nickel oxide conducts electricity.':'The Shestopalov group showed how surface treatment changes nickel oxide conductivity.');};
  await run('draft()');
  assert.equal(requests.length,2,'a first-person or unattributed model answer receives one correction');
  assert.ok(requests[0].system.includes('never assume')||requests[0].system.includes('Never assume'));
  assert.ok(requests[0].system.includes('Shestopalov group'));
  assert.equal(run('currentGraphic.figure'),'selected-ai-image','caption generation must retain the selected image');
  assert.equal(run('currentGraphic.template'),'art');assert.equal(run('current.alt_text'),'Conceptual thin film');
  assert.match(run('current.caption'),/^The Shestopalov group/);assert.match(run('current.caption'),/link in bio/);
  assert.equal(run('activeTab'),'caption');assert.match(fields.draftBtn.textContent,/keep image/);
  const previous=run('current.caption');let calls=0;context.fetch=async()=>{calls++;return response('We found this result.');};
  await run('draft()');assert.equal(calls,2,'correction attempts are bounded');assert.equal(run('current.caption'),previous,'a failed correction must preserve the previous reviewed caption');assert.equal(run('currentGraphic.figure'),'selected-ai-image');assert.match(fields.srcErr.innerHTML,/research credit corrected/);
  context.fetch=async()=>{fields.paperText.value='Different source entered while waiting.';return response('The Shestopalov group studied the film.');};
  await run('draft()');assert.equal(run('current.caption'),previous,'a stale response must not overwrite a changed source');
  // DOI metadata must retain authors beyond the old four-name cutoff, including Rochester authors.
  fields.paperCredit.value='';run('paperMeta=null;reviewSource=null;');
  context.fetch=async()=>({ok:true,json:async()=>({message:{title:['Complete author test'],author:[...Array.from({length:5},(_,n)=>({given:'Author',family:String(n)})),{given:'Alexander',family:'Shestopalov',affiliation:[{name:'University of Rochester'}]}],'container-title':['Chemistry of Materials'],published:{'date-parts':[[2026]]},abstract:'A grounded abstract.'}})});
  await run('fetchDoi()');assert.match(run('paperMeta.authors'),/Alexander Shestopalov/);assert.equal(fields.paperCredit.value,'Alexander Shestopalov');assert.match(run('buildBrief().brief'),/Alexander Shestopalov/);
  run('reviewSource={type:"Paper",credit:"Shestopalov group"};');assert.equal(run('defaultPaperCredit_()'),'Shestopalov group');
  console.log('Paper image carryover, author metadata, caption correction, bio references and stale responses passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
